export const STATES = [
  "Hawaii",
  "Alaska",
  "Oregon",
  "Washington",
  "California",
  "Nevada",
  "Idaho",
  "Arizona",
  "Montana",
  "Utah",
  "New Mexico",
  "Colorado",
  "Wyoming",
  "North Dakota",
  "South Dakota",
  "Texas",
  "Oklahoma",
  "Nebraska",
  "Kansas",
  "Iowa",
  "Minnesota",
  "Arkansas",
  "Missouri",
  "Louisiana",
  "Mississippi",
  "Illinois",
  "Wisconsin",
  "Tennessee",
  "Alabama",
  "Indiana",
  "Kentucky",
  "Michigan",
  "Georgia",
  "Florida",
  "Ohio",
  "West Virginia",
  "South Carolina",
  "North Carolina",
  "Virginia",
  "District of Columbia",
  "Pennsylvania",
  "Maryland",
  "Delaware",
  "New Jersey",
  "New York",
  "Connecticut",
  "Vermont",
  "New Hampshire",
  "Rhode Island",
  "Massachusetts",
  "Maine",
  "Puerto Rico"
];
