const {Client} = require("mondrian-rest-client");
const d3Array = require("d3-array");
const sequelize = require("sequelize");
const shell = require("shelljs");
const path = require("path");
const Op = sequelize.Op;

const client = new Client(process.env.CANON_LOGICLAYER_CUBE);

const topicTypeDir = path.join(__dirname, "../components/topics/");

const profileReqTreeOnly = {
  attributes: ["id", "title", "slug", "dimension", "ordering"],
  include: [
    {
      association: "sections", attributes: ["id", "title", "slug", "ordering", "profile_id"],
      include: [
        {association: "topics", attributes: ["id", "title", "slug", "ordering", "section_id", "type"]}
      ]
    }
  ]
};

const storyReqTreeOnly = {
  attributes: ["id", "title", "ordering"],
  include: [
    {
      association: "storytopics", attributes: ["id", "title", "slug", "ordering", "story_id", "type"]
    }
  ]
};

const formatterReqTreeOnly = {
  attributes: ["id", "name"]
};

const profileReqProfileOnly = {
  include: [
    {association: "generators", attributes: ["id", "name"]},
    {association: "materializers", attributes: ["id", "name", "ordering"]},
    {association: "stats", attributes: ["id", "ordering"]},
    {association: "footnotes", attributes: ["id", "ordering"]}
  ]
};

const storyReqStoryOnly = {
  include: [
    {association: "authors", attributes: ["id", "ordering"]},
    {association: "descriptions", attributes: ["id", "ordering"]},
    {association: "footnotes", attributes: ["id", "ordering"]}
  ]
};

const sectionReqSectionOnly = {
  include: [
    {association: "subtitles", attributes: ["id", "ordering"]},
    {association: "descriptions", attributes: ["id", "ordering"]}
  ]
};

const topicReqTopicOnly = {
  include: [
    {association: "subtitles", attributes: ["id", "ordering"]},
    {association: "descriptions", attributes: ["id", "ordering"]},
    {association: "visualizations", attributes: ["id", "ordering"]},
    {association: "stats", attributes: ["id", "ordering"]},
    {association: "selectors"}
  ]
};

const storyTopicReqStoryTopicOnly = {
  include: [
    {association: "subtitles", attributes: ["id", "ordering"]},
    {association: "descriptions", attributes: ["id", "ordering"]},
    {association: "visualizations", attributes: ["id", "ordering"]},
    {association: "stats", attributes: ["id", "ordering"]}
  ]
};

/**
 * API paths are dynamically generated by folding over this list in the get/post methods that follow.
 * IMPORTANT: When new tables are added to the CMS, adding their exact tablename to this list will
 * automatically generate Create, Update, and Delete Routes (as specified later in the get/post methods)
 */
const cmsTables = [
  "author", "formatter", "generator", "materializer", "profile",
  "profile_footnote", "profile_stat", "section", "section_description",
  "section_subtitle", "selector", "story", "story_description", "story_footnote", "storytopic",
  "storytopic_description", "storytopic_stat", "storytopic_subtitle", "storytopic_visualization",
  "topic", "topic_description", "topic_stat", "topic_subtitle", "topic_visualization"
];

const sorter = (a, b) => a.ordering - b.ordering;

/**
 * Due to yet-unreproducible edge cases, sometimes elements lose their ordering. 
 * This function sorts an array, then checks if the "ordering" property lines up 
 * with the element's place in the array. If not, "patch" the element and send it back
 * to the client, and asynchronously send an update to the db to match it.
 */
const flatSort = (conn, array) => {
  if (!array) return [];
  array.sort(sorter).map((o, i) => {
    if (o.ordering !== i) {
      o.ordering = i;
      conn.update({ordering: i}, {where: {id: o.id}});
    }
    return o;
  });
  return array;
};


// Using nested ORDER BY in the massive includes is incredibly difficult so do it manually here. todo: move it up to the query.
const sortProfileTree = (db, profiles) => {
  profiles = profiles.map(p => p.toJSON());
  profiles = flatSort(db.profile, profiles);
  profiles.forEach(p => {
    p.sections = flatSort(db.section, p.sections);
    p.sections.forEach(s => {
      s.topics = flatSort(db.topic, s.topics);
    });
  });
  return profiles;
};

const sortStoryTree = (db, stories) => {
  stories = stories.map(s => s.toJSON());
  stories = flatSort(db.story, stories);
  stories.forEach(s => {
    s.storytopics = flatSort(db.storytopic, s.storytopics);
  });
  return stories;
};

const sortProfile = (db, profile) => {
  profile = profile.toJSON();
  profile.materializers = flatSort(db.materializer, profile.materializers);
  profile.stats = flatSort(db.profile_stat, profile.stats);
  profile.footnotes = flatSort(db.profile_footnote, profile.footnotes);
  return profile;
};

const sortStory = (db, story) => {
  story = story.toJSON();
  story.descriptions = flatSort(db.story_description, story.descriptions);
  story.footnotes = flatSort(db.story_footnote, story.footnotes);
  story.authors = flatSort(db.author, story.authors);
  return story;
};

const sortSection = (db, section) => {
  section = section.toJSON();
  section.subtitles = flatSort(db.section_subtitle, section.subtitles);
  section.descriptions = flatSort(db.section_description, section.descriptions);
  return section;
};

const sortTopic = (db, topic) => {
  topic = topic.toJSON();
  topic.subtitles = flatSort(db.topic_subtitle, topic.subtitles);
  topic.visualizations = flatSort(db.topic_visualization, topic.visualizations);
  topic.stats = flatSort(db.topic_stat, topic.stats);
  topic.descriptions = flatSort(db.topic_description, topic.descriptions);
  topic.selectors = flatSort(db.selector, topic.selectors);
  return topic;
};

const sortStoryTopic = (db, storytopic) => {
  storytopic = storytopic.toJSON();
  storytopic.subtitles = flatSort(db.storytopic_subtitle, storytopic.subtitles);
  storytopic.visualizations = flatSort(db.storytopic_visualization, storytopic.visualizations);
  storytopic.stats = flatSort(db.storytopic_stat, storytopic.stats);
  storytopic.descriptions = flatSort(db.storytopic_description, storytopic.descriptions);
  return storytopic;
};

const formatter = (members, data, dimension, level) => {

  const newData = members.reduce((arr, d) => {
    const obj = {};
    obj.id = `${d.key}`;
    obj.name = d.name;
    obj.display = d.caption;
    obj.zvalue = data[obj.id] || 0;
    obj.dimension = dimension;
    obj.hierarchy = level;
    obj.stem = -1;
    arr.push(obj);
    return arr;
  }, []);
  const st = d3Array.deviation(newData, d => d.zvalue);
  const average = d3Array.median(newData, d => d.zvalue);
  newData.forEach(d => d.zvalue = (d.zvalue - average) / st);
  return newData;
};

const pruneSearch = async(dimension, db) => {
  const currentProfiles = await db.profile.findAll();
  const currentDimensions = currentProfiles.map(p => p.dimension);
  // To be on the safe side, only clear the search table of dimensions that NO remaining
  // profiles are currently making use of.
  if (!currentDimensions.includes(dimension)) {
    const resp = await db.search.destroy({where: {dimension}});
    console.log(`Cleaned up search data. Rows affected: ${resp}`);
  }
};

const populateSearch = (profileData, db) => {

  /**
   *
   */
  async function start() {

    const cubeName = profileData.cubeName;
    const measure = profileData.measure;
    const dimension = profileData.dimName;
    const dimLevels = profileData.levels;

    const cube = await client.cube(cubeName);

    const levels = cube.dimensionsByName[dimension].hierarchies[0].levels
      .filter(l => l.name !== "(All)" && dimLevels.includes(l.name));

    let fullList = [];
    for (let i = 0; i < levels.length; i++) {

      const level = levels[i];
      const members = await client.members(level);

      const data = await client.query(cube.query
        .drilldown(dimension, level.hierarchy.name, level.name)
        .measure(measure), "jsonrecords")
        .then(resp => resp.data.data)
        .then(data => data.reduce((obj, d) => {
          obj[d[`ID ${level.name}`]] = d[measure];
          return obj;
        }, {}));

      fullList = fullList.concat(formatter(members, data, dimension, level.name));

    }

    for (let i = 0; i < fullList.length; i++) {
      const obj = fullList[i];
      const {id, dimension, hierarchy} = obj;
      const [row, created] = await db.search.findOrCreate({
        where: {id, dimension, hierarchy},
        defaults: obj
      });
      if (created) console.log(`Created: ${row.id} ${row.display}`);
      else {
        await row.updateAttributes(obj);
        console.log(`Updated: ${row.id} ${row.display}`);
      }
    }

  }

  start();

};

module.exports = function(app) {

  const {db} = app.settings;

  /* GETS */

  app.get("/api/cms/tree", async(req, res) => {
    let profiles = await db.profile.findAll(profileReqTreeOnly);
    profiles = sortProfileTree(db, profiles);
    res.json(profiles).end();
  });

  app.get("/api/cms/storytree", async(req, res) => {
    let stories = await db.story.findAll(storyReqTreeOnly);
    stories = sortStoryTree(db, stories);
    res.json(stories).end();
  });

  app.get("/api/cms/formattertree", (req, res) => {
    db.formatter.findAll(formatterReqTreeOnly).then(formatters => {
      res.json(formatters).end();
    });
  });

  app.get("/api/cms/profile/get/:id", async(req, res) => {
    const {id} = req.params;
    const reqObj = Object.assign({}, profileReqProfileOnly, {where: {id}});
    const profile = await db.profile.findOne(reqObj);
    res.json(sortProfile(db, profile)).end();
  });

  app.get("/api/cms/story/get/:id", async(req, res) => {
    const {id} = req.params;
    const reqObj = Object.assign({}, storyReqStoryOnly, {where: {id}});
    const story = await db.story.findOne(reqObj);
    res.json(sortStory(db, story)).end();
  });

  app.get("/api/cms/section/get/:id", async(req, res) => {
    const {id} = req.params;
    const reqObj = Object.assign({}, sectionReqSectionOnly, {where: {id}});
    const section = await db.section.findOne(reqObj);
    res.json(sortSection(db, section)).end();
  });

  app.get("/api/cms/topic/get/:id", async(req, res) => {
    const {id} = req.params;
    const reqObj = Object.assign({}, topicReqTopicOnly, {where: {id}});
    let topic = await db.topic.findOne(reqObj);
    const topicTypes = [];
    shell.ls(`${topicTypeDir}*.jsx`).forEach(file => {
      const compName = file.replace(topicTypeDir, "").replace(".jsx", "");
      topicTypes.push(compName);
    });
    topic = sortTopic(db, topic);
    topic.types = topicTypes;
    res.json(topic).end();
  });

  app.get("/api/cms/storytopic/get/:id", async(req, res) => {
    const {id} = req.params;
    const reqObj = Object.assign({}, storyTopicReqStoryTopicOnly, {where: {id}});
    let storytopic = await db.storytopic.findOne(reqObj);
    const topicTypes = [];
    shell.ls(`${topicTypeDir}*.jsx`).forEach(file => {
      const compName = file.replace(topicTypeDir, "").replace(".jsx", "");
      topicTypes.push(compName);
    });
    storytopic = sortStoryTopic(db, storytopic);
    storytopic.types = topicTypes;
    res.json(storytopic).end();
  });

  // Top-level tables have their own special gets, so exclude them from the "simple" gets
  const getList = cmsTables.filter(tableName =>
    !["profile", "section", "topic", "story", "storytopic"].includes(tableName)
  );

  getList.forEach(ref => {
    app.get(`/api/cms/${ref}/get/:id`, (req, res) => {
      db[ref].findOne({where: {id: req.params.id}}).then(u => res.json(u).end());
    });
  });

  /* INSERTS */
  // For now, all "create" commands are identical, and don't need a filter (as gets do above), so we may use the whole list.
  const newList = cmsTables;
  newList.forEach(ref => {
    app.post(`/api/cms/${ref}/new`, (req, res) => {
      db[ref].create(req.body).then(u => res.json(u));
    });
  });

  app.post("/api/cms/profile/newScaffold", (req, res) => {
    const profileData = req.body;
    db.profile.create({slug: profileData.slug, ordering: profileData.ordering, dimension: profileData.dimName}).then(profile => {
      db.section.create({ordering: 0, profile_id: profile.id}).then(section => {
        db.topic.create({ordering: 0, section_id: section.id}).then(() => {
          db.profile.findAll(profileReqTreeOnly).then(profiles => {
            profiles = sortProfileTree(db, profiles);
            populateSearch(profileData, db);
            res.json(profiles).end();
          });
        });
      });
    });
  });

  /* UPDATES */
  // For now, all "update" commands are identical, and don't need a filter (as gets do above), so we may use the whole list.
  const updateList = cmsTables;
  updateList.forEach(ref => {
    app.post(`/api/cms/${ref}/update`, (req, res) => {
      db[ref].update(req.body, {where: {id: req.body.id}}).then(u => res.json(u));
    });
  });

  /* DELETES */
  /**
   * To streamline deletes, this list contains objects with two properties. "elements" refers to the tables to be modified,
   * and "parent" refers to the foreign key that need be referenced in the associated where clause.
   */
  const deleteList = [
    {elements: ["profile_footnote", "profile_stat"], parent: "profile_id"},
    {elements: ["section_description", "section_subtitle"], parent: "section_id"},
    {elements: ["author", "story_description", "story_footnote"], parent: "story_id"},
    {elements: ["topic_subtitle", "topic_description", "topic_stat", "topic_visualization"], parent: "topic_id"}
  ];

  deleteList.forEach(list => {
    list.elements.forEach(ref => {
      app.delete(`/api/cms/${ref}/delete`, (req, res) => {
        db[ref].findOne({where: {id: req.query.id}}).then(row => {
          // Construct a where clause that looks someting like: {profile_id: row.profile_id, ordering: {[Op.gt]: row.ordering}}
          // except "profile_id" is the "parent" in the array above
          const where1 = {ordering: {[Op.gt]: row.ordering}};
          where1[list.parent] = row[list.parent];
          db[ref].update({ordering: sequelize.literal("ordering -1")}, {where: where1}).then(() => {
            db[ref].destroy({where: {id: req.query.id}}).then(() => {
              const where2 = {};
              where2[list.parent] = row[list.parent];
              db[ref].findAll({where: where2, attributes: ["id", "ordering"], order: [["ordering", "ASC"]]}).then(rows => {
                res.json(rows).end();
              });
            });
          });
        });
      });
    });
  });

  // Other (More Complex) Elements
  app.delete("/api/cms/generator/delete", (req, res) => {
    db.generator.findOne({where: {id: req.query.id}}).then(row => {
      db.generator.destroy({where: {id: req.query.id}}).then(() => {
        db.generator.findAll({where: {profile_id: row.profile_id}, attributes: ["id", "name"]}).then(rows => {
          res.json(rows).end();
        });
      });
    });
  });

  app.delete("/api/cms/materializer/delete", (req, res) => {
    db.materializer.findOne({where: {id: req.query.id}}).then(row => {
      db.materializer.update({ordering: sequelize.literal("ordering -1")}, {where: {profile_id: row.profile_id, ordering: {[Op.gt]: row.ordering}}}).then(() => {
        db.materializer.destroy({where: {id: req.query.id}}).then(() => {
          db.materializer.findAll({where: {profile_id: row.profile_id}, attributes: ["id", "ordering", "name"], order: [["ordering", "ASC"]]}).then(rows => {
            res.json(rows).end();
          });
        });
      });
    });
  });

  app.delete("/api/cms/profile/delete", (req, res) => {
    db.profile.findOne({where: {id: req.query.id}}).then(row => {
      db.profile.update({ordering: sequelize.literal("ordering -1")}, {where: {ordering: {[Op.gt]: row.ordering}}}).then(() => {
        db.profile.destroy({where: {id: req.query.id}}).then(() => {
          pruneSearch(row.dimension, db);
          db.profile.findAll(profileReqTreeOnly).then(profiles => {
            profiles = sortProfileTree(db, profiles);
            res.json(profiles).end();
          });
        });
      });
    });
  });

  app.delete("/api/cms/story/delete", (req, res) => {
    db.story.findOne({where: {id: req.query.id}}).then(row => {
      db.story.update({ordering: sequelize.literal("ordering -1")}, {where: {ordering: {[Op.gt]: row.ordering}}}).then(() => {
        db.story.destroy({where: {id: req.query.id}}).then(() => {
          db.story.findAll(storyReqTreeOnly).then(stories => {
            stories = sortStoryTree(db, stories);
            res.json(stories).end();
          });
        });
      });
    });
  });

  app.delete("/api/cms/formatter/delete", (req, res) => {
    db.formatter.destroy({where: {id: req.query.id}}).then(() => {
      db.formatter.findAll({attributes: ["id", "name", "description"]}).then(rows => {
        res.json(rows).end();
      });
    });
  });

  app.delete("/api/cms/section/delete", (req, res) => {
    db.section.findOne({where: {id: req.query.id}}).then(row => {
      db.section.update({ordering: sequelize.literal("ordering -1")}, {where: {profile_id: row.profile_id, ordering: {[Op.gt]: row.ordering}}}).then(() => {
        db.section.destroy({where: {id: req.query.id}}).then(() => {
          db.section.findAll({
            where: {profile_id: row.profile_id},
            attributes: ["id", "title", "slug", "ordering", "profile_id"],
            order: [["ordering", "ASC"]],
            include: [
              {association: "topics", attributes: ["id", "title", "slug", "ordering", "section_id"]}
            ]
          }).then(rows => {
            res.json(rows).end();
          });
        });
      });
    });
  });

  app.delete("/api/cms/topic/delete", (req, res) => {
    db.topic.findOne({where: {id: req.query.id}}).then(row => {
      db.topic.update({ordering: sequelize.literal("ordering -1")}, {where: {section_id: row.section_id, ordering: {[Op.gt]: row.ordering}}}).then(() => {
        db.topic.destroy({where: {id: req.query.id}}).then(() => {
          db.topic.findAll({where: {section_id: row.section_id}, attributes: ["id", "title", "slug", "ordering", "section_id", "type"], order: [["ordering", "ASC"]]}).then(rows => {
            res.json(rows).end();
          });
        });
      });
    });
  });

  app.delete("/api/cms/storytopic/delete", (req, res) => {
    db.storytopic.findOne({where: {id: req.query.id}}).then(row => {
      db.storytopic.update({ordering: sequelize.literal("ordering -1")}, {where: {story_id: row.story_id, ordering: {[Op.gt]: row.ordering}}}).then(() => {
        db.storytopic.destroy({where: {id: req.query.id}}).then(() => {
          db.storytopic.findAll({where: {story_id: row.story_id}, attributes: ["id", "title", "slug", "ordering", "story_id", "type"], order: [["ordering", "ASC"]]}).then(rows => {
            res.json(rows).end();
          });
        });
      });
    });
  });

  app.delete("/api/cms/selector/delete", (req, res) => {
    db.selector.findOne({where: {id: req.query.id}}).then(row => {
      db.selector.update({ordering: sequelize.literal("ordering -1")}, {where: {topic_id: row.topic_id, ordering: {[Op.gt]: row.ordering}}}).then(() => {
        db.selector.destroy({where: {id: req.query.id}}).then(() => {
          db.selector.findAll({where: {topic_id: row.topic_id}, order: [["ordering", "ASC"]]}).then(rows => {
            res.json(rows).end();
          });
        });
      });
    });
  });

};
