// Loading Dispatches
export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";

// Auth Dispatches
export const ACTIVATE_SEND_FAILURE = "ACTIVATE_SEND_FAILURE";
export const ACTIVATE_SEND_REQUEST = "ACTIVATE_SEND_REQUEST";
export const ACTIVATE_SEND_SUCCESS = "ACTIVATE_SEND_SUCCESS";
export const ACTIVATE_TOKEN_FAILURE = "ACTIVATE_TOKEN_FAILURE";
export const ACTIVATE_TOKEN_SUCCESS = "ACTIVATE_TOKEN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const RESET_PW_FAILURE = "RESET_PW_FAILURE";
export const RESET_PW_SUCCESS = "RESET_PW_SUCCESS";
export const RESET_SEND_FAILURE = "RESET_SEND_FAILURE";
export const RESET_SEND_REQUEST = "RESET_SEND_REQUEST";
export const RESET_SEND_SUCCESS = "RESET_SEND_SUCCESS";
export const RESET_TOKEN_SUCCESS = "RESET_TOKEN_SUCCESS";
export const RESET_TOKEN_FAILURE = "RESET_TOKEN_FAILURE";
export const SIGNUP_EXISTS = "SIGNUP_EXISTS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const WRONG_PW = "WRONG_PW";
